FROM debian:latest

ARG pkg_set

# net-tools -> ifconfig ; 
RUN apt-get update

### NET ###
# curl wget
# ping
# ifconfig
# nslookup
RUN if [ ! -z "$pkg_set" ]; then \
        if [ "x$pkg_set" = "xnet" ] ; then \
            apt-get install -y \
            curl wget \
            iputils-ping \
            net-tools \
            dnsutils \
            ; \
        fi \
    fi
 